# Generated by Django 4.1 on 2022-08-31 13:36

from django.db import migrations, models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id_carro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_carro', models.CharField(max_length=255)),
                ('marca_carro', models.CharField(max_length=255)),
                ('potencia_carro', models.IntegerField()),
                ('ano_carro', models.IntegerField()),
                ('preco_carro', models.DecimalField(decimal_places=2, max_digits=13)),
                ('foto_carro', stdimage.models.StdImageField(force_min_size=False, upload_to='%y/%m/%d', variations={})),
            ],
        ),
    ]
