# Generated by Django 4.1 on 2022-10-18 13:07

from django.db import migrations, models
import pictures.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id_carro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_carro', models.CharField(max_length=255)),
                ('marca_carro', models.CharField(max_length=255)),
                ('potencia_carro', models.IntegerField()),
                ('ano_carro', models.IntegerField()),
                ('preco_carro', models.DecimalField(decimal_places=2, max_digits=13)),
                ('foto_carro', pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='media/cars/images')),
            ],
        ),
    ]
